# Generated by Django 5.1.1 on 2024-10-03 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("food", models.CharField(max_length=255)),
                ("time", models.DateField(auto_now_add=True)),
                ("feelings", models.TextField()),
                ("food_intensity", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="MoodEntry",
        ),
    ]
