# Generated by Django 5.1.1 on 2024-10-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_foodentry_delete_moodentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodentry',
            old_name='feelings',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='foodentry',
            old_name='food_intensity',
            new_name='rating',
        ),
    ]
