# Generated by Django 5.1.1 on 2024-10-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_feelings_foodentry_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='time',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='comments',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='contact_number',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='food_type',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='location',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='menu_info',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='reviews_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='street_address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='trip_advisor_url',
            field=models.URLField(default='N/A'),
        ),
    ]
