# Generated by Django 5.1.2 on 2024-10-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_foodentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='image_url',
            field=models.URLField(default='N/A'),
        ),
    ]
