# Generated by Django 5.1.2 on 2024-10-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_foodentry_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='image_url',
            field=models.URLField(default='N/A', max_length=255),
        ),
    ]
