# Generated by Django 5.1.2 on 2024-10-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_foodentry_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='user',
        ),
    ]
