# Generated by Django 5.1.1 on 2024-10-24 15:48

from django.db import migrations
from django.core.management import call_command


class Migration(migrations.Migration):
    def load_my_initial_data(apps, schema_editor):
        call_command("loaddata", "main/fixtures/food_database.json")

    dependencies = [
        ('main', '0007_alter_foodentry_image_url'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]

