# Generated by Django 5.1.1 on 2024-10-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_foodentry_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='number_of_reviews',
            field=models.IntegerField(default=1),
        ),
    ]
