# Generated by Django 5.1.1 on 2024-10-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_foodentry_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
