# Generated by Django 5.1 on 2024-12-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_foodentry_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='avg_rating',
            field=models.CharField(max_length=10),
        ),
    ]
