# Generated by Django 5.1.4 on 2024-12-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20241221_2156'),
        ('main', '0016_auto_20241222_1645'),
    ]

    operations = [
    ]
