# Generated by Django 5.1.1 on 2024-10-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default='no title', max_length=50),
        ),
    ]
