# Generated by Django 5.1.1 on 2024-10-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
