# Generated by Django 5.1.2 on 2024-10-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
