# Generated by Django 5.1.2 on 2024-10-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_role', '0002_profile_last_password_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='class1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='npm',
        ),
    ]
